[package]
name = "rust-jni-generator"
version = "0.1.0"
authors = ["Monnoroch <monnoroch@gmail.com>"]

[dependencies]
quote = "0.6.4"
proc-macro2 = "0.4.9"

[dev-dependencies]
rust-jni = { path = "../../rust-jni" }

[lib]
proc-macro = true
