sudo: false
dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
env:
  global:
    - LD_LIBRARY_PATH="$JAVA_HOME/jre/lib/amd64/server"
  matrix:
    - JDK=oraclejdk8
    - JDK=openjdk8
before_script:
  - ./ci/install-java.sh
  - jdk_switcher use $JDK
install:
  - rustup component add rustfmt
script:
  - ci/check-format.sh
  - ci/test.sh
jobs:
  include:
    - stage: "Test release versions of all crates"
      if: fork = false AND branch = master AND commit_message ~= /!sudo publish (rust-jni)/
      rust: nightly
      jdk: openjdk8
      before_script:
        - jdk_switcher use $JDK
      script:
        - ci/test.sh
        - cargo package
    - stage: "Publish rust-jni"
      if: fork = false AND branch = master AND commit_message ~= /!sudo publish rust-jni/
      rust: stable
      jdk: openjdk8
      script:
        - cargo login $CARGO_TOKEN
        - cargo publish
notifications:
  email: false
