dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
env:
  global:
    - LD_LIBRARY_PATH="$JAVA_HOME/jre/lib/amd64/server"
  matrix:
    - JDK=oraclejdk8
    - JDK=openjdk8
before_script:
  - jdk_switcher use $JDK
install:
  - rustup component add rustfmt-preview
script:
  - ci/check-format.sh
  - ci/test.sh
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email: false
