language: rust
rust:
  - stable
  - beta
  - nightly
install:
  - rustup component add rustfmt-preview
script:
  - if [[ ${TRAVIS_RUST_VERSION} == "stable" ]]; then rustfmt --error-on-unformatted --write-mode diff src/lib.rs; fi
  - cargo test --verbose
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email: false
