[package]
name = "rust-jni"
version = "0.1.0"
authors = ["Monnoroch <monnoroch@gmail.com>"]

[dependencies]
cesu8 = "1.1.0"
jni-sys = "0.3.0"

[dev-dependencies]
lazy_static = "1"

[build-dependencies]
walkdir = "2"

[features]
libjvm = []
